-- 코드를 입력하세요
SELECT a.AUTHOR_ID AS AUTHOR_ID, a.AUTHOR_NAME AS AUTHOR_NAME, b.CATEGORY AS CATEGORY, SUM(b.PRICE *s.SALES) AS TOTAL_SALES
FROM BOOK b JOIN AUTHOR a ON b.AUTHOR_ID = a.AUTHOR_ID
            JOIN BOOK_SALES s ON b.BOOK_ID = s.BOOK_ID
WHERE DATE_FORMAT(s.SALES_DATE, '%Y-%m') = '2022-01'
GROUP BY b.CATEGORY, a.AUTHOR_ID
ORDER BY b.AUTHOR_ID , b.CATEGORY DESC;