-- 코드를 입력하세요
SELECT *
FROM (
SELECT c.CAR_ID AS CAR_ID, c.CAR_TYPE AS CAR_TYPE, c.DAILY_FEE * 30 * (100 - p.DISCOUNT_RATE) / 100 AS FEE
FROM (SELECT *
      FROM CAR_RENTAL_COMPANY_CAR
      WHERE CAR_TYPE IN ('세단', 'SUV')) c
JOIN (SELECT *
      FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
      WHERE DURATION_TYPE = '30일 이상') p ON c.CAR_TYPE = p.CAR_TYPE
WHERE NOT EXISTS (SELECT 1
                  FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY h
                  WHERE h.START_DATE <= '2022-11-30' 
                    AND h.END_DATE >= '2022-11-01'
                    AND c.CAR_ID = h.CAR_ID)
    ) t
WHERE FEE >= 500000 AND FEE < 2000000
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC