-- 코드를 입력하세요
SELECT YEAR(o.SALES_DATE) AS YEAR, MONTH(o.SALES_DATE) AS MONTH, u.GENDER AS GENDER, COUNT(DISTINCT o.USER_ID) AS USERS
FROM ONLINE_SALE o JOIN USER_INFO u ON o.USER_ID = u.USER_ID
GROUP BY YEAR(o.SALES_DATE), MONTH(o.SALES_DATE), u.GENDER
HAVING u.GENDER IS NOT NULL
ORDER BY YEAR, MONTH, GENDER

# SELECT *
# FROM ONLINE_SALE