-- 코드를 작성해주세요
SELECT DISTINCT d.ID AS ID, d.EMAIL AS EMAIL, d.FIRST_NAME AS FIRST_NAME, d.LAST_NAME AS LAST_NAME
FROM DEVELOPERS AS d JOIN SKILLCODES AS s ON d.SKILL_CODE & s.CODE > 0
WHERE s.CATEGORY LIKE 'Front End'
ORDER BY d.ID