-- 코드를 입력하세요
SELECT u.USER_ID AS USER_ID, u.NICKNAME AS NICKNAME, SUM(IF(b.STATUS = 'DONE', PRICE, 0)) AS TOTAL_SALES
FROM USED_GOODS_USER AS u LEFT OUTER JOIN USED_GOODS_BOARD AS b ON u.USER_ID = b.WRITER_ID
GROUP BY u.USER_ID
HAVING TOTAL_SALES >= 700000
ORDER BY TOTAL_SALES