-- 코드를 입력하세요
SELECT DISTINCT c.CAR_ID
FROM (SELECT *
      FROM CAR_RENTAL_COMPANY_CAR
      WHERE CAR_TYPE = '세단') c
WHERE EXISTS (SELECT 1
              FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY h
              WHERE c.CAR_ID = h.CAR_ID
                AND h.START_DATE >= '2022-10-01'
                AND h.START_DATE <= '2022-10-30')
ORDER BY c.CAR_ID DESC